### ISSUE TITLE
[BUG] Mongodb - unable to connect to mongo without user

### ISSUE THREAD

**Issue by anthosz** [clidey/whodb#141]
Hello,

I just init a "fake" cluster of mongodb:
```
  mongo:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}) }" | mongosh --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    restart: always
```

Due to the fact it's dev/playground, there is no credential at all.

If I try to connect to it via mongo-express and url: mongodb://mongo:27017/?ssl=false, all ok.

If I try via whodb, it didn't works, seems the user is mandatory:
![image](https://github.com/user-attachments/assets/4a481d4d-fcd4-4319-a503-728ccbed6d72)

Best regards,
