### ISSUE TITLE
[FR] To support custom port in the environment variables

### ISSUE THREAD

**Issue by raymond-xu-gtg** [clidey/whodb#169]
For now I see with JSONs like
```
    environment:
      WHODB_POSTGRES_1: '{"host":"localhost","user":"user","password":"password","database":"postgres"}'
      WHODB_MYSQL: '[{"host":"localhost","user":"user","password":"password","database":"mysql"}]'
      WHODB_SQLITE3_1: '{"database":"sample.db"}'
```
I can configure a list of profiles. Can we add support for custom port in the JSON? eg.
```
      WHODB_MYSQL: '[{"host":"localhost","user":"user","password":"password","database":"mysql", "port": 13306}]'
```

Cheers
Ray
