### ISSUE TITLE
[BUG] - OpenAI Compatible endpoint env variable not working

### ISSUE THREAD

**Issue by nicopace** [clidey/whodb#496]
**Describe the bug**
The environment variable that allows to set an OpenAI compatible endpoint doesn't work.

**To Reproduce**
Defined a docker compose like this:
```
version: "3.8"
services:
  whodb:
    image: clidey/whodb
    volumes:
      - ./sample.db:/db/sample.db
    environment:
      - WHODB_OPENAI_COMPATIBLE_API_KEY=...
      - WHODB_OPENAI_COMPATIBLE_ENDPOINT=https://generativelanguage.googleapis.com/v1beta/openai/
      - WHODB_CUSTOM_MODELS=gemini-2.0-flash
    ports:
      - "8080:8080"
```

**Expected behavior**
For the model to be available in Houdini.

**Screenshots**

<img width="601" alt="Image" src="https://github.com/user-attachments/assets/85839f79-4b7d-4cd2-96e7-4e8341b95be7" />

The add external model doesn't allow to add a custom endpoint either.
